### ISSUE TITLE
Customer show page

### ISSUE THREAD

**Issue by DmitryLeviossa** [DmitryLeviossa/leviossa#17]

**Comment by DmitryLeviossa** [comment]
That page will has all info about customer, all his projects, all users that worker for that customer.
- [ ] Show page header - Customer Name
- [ ] Section with different background and all plain info from db
- [ ] Table with projects
- [ ] Table with users

**Comment by DmitryLeviossa** [comment]
![2018-05-11 15 59 31 2](https://user-images.githubusercontent.com/38185664/39925435-54253c7c-5534-11e8-9655-5fba4a75777c.png)

**Comment by AlexLeviossa** [comment]
https://github.com/DmitryLeviossa/leviossa/pull/62
