### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by DmitryLeviossa** [DmitryLeviossa/leviossa#33]
All users will have feedbacks. In future only admins can add that feedbacks, for now just add link to actions 'feedback', on click we will show modal with textarea and score (from 0 to 10), by default score is 1. Admin will set new score and text feedback, after it will be send to server and will be shown at user show page.

feedbacks table:
user_id - user that give feedback
author_id - user that created feedback
feedback - text from textarea
score - integer form 0 to 10

add new integer field to user - score, after submit/edit/delete feedback it will be updated with triggers, see example on projects.

**Comment by AlexLeviossa** [comment]
https://github.com/DmitryLeviossa/leviossa/pull/39
